session_id = 'tokinasin'
start_at = 2025-11-02T17:00:00+09:00
end_at = 2025-11-02T17:05:00+09:00
speaker_name = 'tokinasin'
title = 'Taking a Productive Break in Vim'
abstract = '''
Vimでの作業中、エディタを離れずに少しだけ息抜きをしたくなったことはありませんか？

ボードゲームが好きな私はVimで遊べるリバーシを探していましたが、かつて存在したプラグインは現在公開されていませんでした。そこで「無いなら作ってしまえ」と、自作プラグイン開発に挑戦しました。

こだわったのは、外部依存なく動作する手強いCPUです。弱い相手では、ゲームはすぐに退屈な作業になってしまいます。しかし、単に強い思考エンジンを実装するだけではレスポンスが遅くなり、快適なゲーム体験を損ないます。

本発表では、この「強さ」と「速度」を両立させるための工夫についてご紹介いたします。
'''
