// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var hide_details, show_details, table;
    table = $('.timetable');
    $.getJSON('./data/schedules.json', function(data) {
      var s, _fn, _i, _len, _ref;
      _ref = data['schedules'];
      _fn = function(s) {
        var hour, min, row, speaker, speakers, t, td, th, theme, time, title;
        t = new Date();
        time = new Date((s['scheduled_at'] + t.getTimezoneOffset() * 60) * 1000);
        title = s['title'];
        speakers = ((function() {
          var _j, _len1, _ref1, _results;
          _ref1 = s['speakers'] != null ? s['speakers'] : s['speakers'] = [];
          _results = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            speaker = _ref1[_j];
            _results.push((speaker['avatar'] ? '<img src="' + speaker['avatar'] + '" class="avatar" /> ' : '') + speaker['name'] + (speaker['twitter'] ? '<a class="btn btn-default btn-xs" href="https://twitter.com/' + speaker['twitter'] + '">twitter</a>' : '') + (speaker['github'] ? '<a class="btn btn-default btn-xs" href="https://github.com/' + speaker['github'] + '">github</a>' : ''));
          }
          return _results;
        })()).join(' / ');
        theme = s['theme'] != null ? s['theme'] : s['theme'] = 'default';
        hour = time.getHours() + 9;
        min = time.getMinutes();
        if (min === 0) {
          min = '00';
        }
        th = hour + ':' + min + ' JST';
        if (s['type'] === 'presentation') {
          td = '<strong>' + title + '</strong><span class="speaker">' + speakers + '</span>';
          if (s['details']) {
            td += '<div class="panel panel-default"><div class="panel-body">';
            td += s['details'];
            if (s['details-i18n']) {
              td += '<hr />' + s['details-i18n'];
            }
            td += '</div></div>';
          }
        }
        if (s['type'] === 'interval') {
          td = title;
          if (s['description']) {
            td += '<div class="panel panel-default"><div class="panel-body">';
            td += s['description'];
            if (s['description-i18n']) {
              td += '<hr />' + s['description-i18n'];
            }
            td += '</div></div>';
          }
        }
        th = '<th>' + th + '</th>';
        td = '<td>' + td + '</td>';
        row = '<tr class="event event-' + theme + '">' + th + td + '</tr>';
        return table.append(row);
      };
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        s = _ref[_i];
        _fn(s);
      }
      return hide_details();
    });
    hide_details = function() {
      $('.show-details').show();
      $('.hide-details').hide();
      return $('table .panel').hide();
    };
    show_details = function() {
      $('.show-details').hide();
      $('.hide-details').show();
      return $('table .panel').show();
    };
    $('.show-details').click(show_details);
    return $('.hide-details').click(hide_details);
  });

}).call(this);
