// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var table;
    table = $('.timetable');
    return $.getJSON('./data/schedules.json', function(data) {
      var s, _i, _len, _ref, _results;
      _ref = data['schedules'];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        s = _ref[_i];
        _results.push((function(s) {
          var row, speaker, speakers, td, th, theme, time, title;
          time = new Date((s['scheduled_at'] + 32400) * 1000);
          title = s['title'];
          speakers = ((function() {
            var _j, _len1, _ref1, _results1;
            _ref1 = s['speakers'] != null ? s['speakers'] : s['speakers'] = [];
            _results1 = [];
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              speaker = _ref1[_j];
              _results1.push(speaker['name']);
            }
            return _results1;
          })()).join(', ');
          theme = s['theme'] != null ? s['theme'] : s['theme'] = 'default';
          console.log(time);
          th = time.getHours() + ':' + time.getMinutes() + ' JST';
          if (s['type'] === 'presentation') {
            td = '<strong>' + title + '</strong><span class="speaker">' + speakers + '</span>';
          }
          if (s['type'] === 'interval') {
            td = title;
          }
          th = '<th>' + th + '</th>';
          td = '<td>' + td + '</td>';
          row = '<tr class="event event-' + theme + '">' + th + td + '</tr>';
          return table.append(row);
        })(s));
      }
      return _results;
    });
  });

}).call(this);
