@ECHO OFF

IF DEFINED NGINX_HOME GOTO HAS_NGINX_HOME
ECHO ERROR: Please define NGINX_HOME environment value.
EXIT /B 1

:HAS_NGINX_HOME

IF EXIST %NGINX_HOME%\nginx.exe GOTO HAS_NGINX_EXE
ECHO ERROR: Please install nginx.exe into %NGINX_HOME%
EXIT /B 1

:HAS_NGINX_EXE
EXIT /B 0
