name: Build and Deploy Jekyll site

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: build with jekyll
        uses: actions/jekyll-build-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site

  deploy:
    needs:
      - build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
